### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by tertsdiepraam**
This PR (hopefully) creates the homepage as in the image at [uutils.github.io]. I've tried to match oranda's style as much as possible and I've copied large parts of their HTML and CSS to make this.

image

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
@sylvestre do you agree with the content of the page? Anything missing?

**Comment by sylvestre** [comment]
yeah, ship it :)
we can always improve it later

**Comment by tertsdiepraam** [comment]
I don't have write access here yet :)

**Comment by sylvestre** [comment]
@tertsdiepraam should be good now

**Comment by tertsdiepraam** [comment]
Failed :(

**Pull request merged**
